# baseURL = 'http://example.org/'
baseURL = "https://www.rndf.me"
languageCode = 'zh-CN'
title = "rndf's blog"

#ä¸»é¢˜
theme = "LoveIt"
# è®¾ç½®é»˜è®¤çš„è¯­è¨€ ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"

# è®¾ç½®æ—¶åŒº
timeZone = "Asia/Shanghai"

# é»˜è®¤æ¯é¡µåˆ—è¡¨æ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®
paginate = 10

# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji = true

# å­—æ•°ç»Ÿè®¡
hasCJKLanguage = true

# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = ""

# ä½œè€…é…ç½®
[author]
name = "æ—¥æš–ç­‰é£"
email = "1061747240@qq.com"
link = ""

# èœå•é…ç½®
[menu]
[[menu.main]]
weight = 1
identifier = "home"
pre = "ğŸ "
post = ""
name = "ä¸»é¡µ"
url = "/"
title = "ä¸»é¡µ"

[[menu.main]]
weight = 2
identifier = "æ–‡ç« "
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
pre = "ğŸ‘¨ğŸ»"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
post = ""
name = "æ–‡ç« "
url = "/posts/"
# å½“æ‚¨å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºæ ‡é¢˜
title = ""

[[menu.main]]
weight = 3
identifier = "tags"
pre = "ğŸ§©"
post = ""
name = "åˆ†ç±»"
url = "/tags/"
title = ""

[[menu.main]]
weight = 4
identifier = "categories"
pre = "ğŸ“š"
post = ""
name = "å½’æ¡£"
url = "/categories"
title = "å½’æ¡£"


[[menu.main]]
weight = 4
identifier = "life"
pre = " ğŸ–"
post = ""
name = "ç”Ÿæ´»"
url = "/posts/life"
title = "ç”Ÿæ´»"

# [[menu.main]]
# weight = 6
# identifier = "about"
# pre = "ğŸ™‹ğŸ»â€â™‚ï¸"
# post = ""
# name = "å…³äº"
# url = "/about/"


[taxonomies]
category = "categories"
# æ ‡ç­¾é¡µé¢çš„ç±»å‹
tag = "tags"
search = "search"

# ä¸»é¢˜é…ç½®
[params]
# ç½‘ç«™é»˜è®¤ä¸»é¢˜ ["auto", "light", "dark"]
defaultTheme = "auto"
dateFormat = "2006-01-02"
# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
# æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
desktopMode = "auto"
# ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
mobileMode = "auto"

# é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
[params.header.title]
# ç½‘ç«™æ ‡é¢˜
name = "æ—¥æš–ç­‰é£"
# ç½‘ç«™æ ‡é¢˜é“¾æ¥
url = "/"
# ç½‘ç«™æ ‡é¢˜å›¾æ ‡
icon = "favicon.ico"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
# pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
post = ""
# æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true


# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
enable = true
# è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
custom = ""
# æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
hugo = false
# æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
copyright = true
# æ˜¯å¦æ˜¾ç¤ºä½œè€…
author = true
# ç½‘ç«™åˆ›ç«‹å¹´ä»½
since = 2023
# ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
icp = ""

# Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
[params.section]
# section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 10

# æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
dateFormat = "01-02"

# List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
[params.list]
# list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 10
dateFormat = "01-02"
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ‘˜è¦
summary = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡ç­¾
tags = true

# æœç´¢é…ç½®
[params.search]
enable = true
# æœç´¢å¼•æ“çš„ç±»å‹ ["lunr", "algolia"]
type = "algolia"
# æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
contentLength = 4000
# æœç´¢æ¡†çš„å ä½æç¤ºè¯­
placeholder = "è¯·è¾“å…¥æœç´¢çš„å…³é”®è¯..."
# æœ€å¤§ç»“æœæ•°ç›®
maxResultLength = 10
# ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
snippetLength = 30
# æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
absoluteURL = false
[params.search.algolia]
index = ""
appID = ""
searchKey = ""

# åº”ç”¨å›¾æ ‡é…ç½®
[params.app]
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
title = "æ—¥æš–ç­‰é£"
# æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
noFavicon = false
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„å›¾æ ‡, è¦†ç›–é»˜è®¤å›¾æ ‡
icon = "favicon.ico"
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„èƒŒæ™¯é¢œè‰², è¦†ç›–é»˜è®¤é¢œè‰²
color = "#ffffff"
# Android æµè§ˆå™¨ä¸»é¢˜è‰²
themeColor = "#ffffff"
# Safari å›¾æ ‡é¢œè‰²
iconColor = "#5bbad5"
# Windows v8-11 ç£è´´é¢œè‰²
tileColor = "#da532c"

# ä¸»é¡µä¿¡æ¯è®¾ç½®
[params.home]
# ä¸»é¡µä¸ªäººä¿¡æ¯
[params.home.profile]
enable = true
# ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
avatarURL = "android-chrome-512x512.png"
# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
title = "æ—¥æš–ç­‰é£"
# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
subtitle = "ä¸ç§¯è·¬æ­¥ï¼Œæ— ä»¥è‡³åƒé‡Œ!"
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = true
# æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
social = true
# ä¸»é¡µæ–‡ç« åˆ—è¡¨
[params.home.posts]
enable = true
# ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 6

# ä¸»é¡µçš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
[params.social]
GitHub = "rinuandengfeng"
email = "1061747240@qq.com"


# æ–‡ç« é¡µé¢å…¨å±€é…ç½®
[params.page]
# æ˜¯å¦ä½¿ç”¨ twemoji
twemoji = true
# æ˜¯å¦ä½¿ç”¨ lightgallery
# lightgallery = true
# æ˜¯å¦æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£å†…å®¹çš„é“¾æ¥
linkToMarkdown = true


# æ–‡ç« é¡µé¢çš„æ ‡é¢˜é…ç½®
[params.page.title]
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜
enable = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„åˆ†ç±»
category = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„æ ‡ç­¾
tags = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„æ—¥æœŸ
date = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„ä½œè€…
author = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„é˜…è¯»æ—¶é•¿
readingTime = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„å­—æ•°
words = true
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ ‡é¢˜çš„è¯„è®ºæ•°
comments = true

# æ–‡ç« é¡µé¢çš„åº•éƒ¨é…ç½®
[params.page.footer]
#æ›´æ–°æ—¶é—´æ ¼å¼
# dateFormat = "2006-01-02"
next = true
pre = true


# ç›®å½•é…ç½®
[params.page.toc]
# æ˜¯å¦ä½¿ç”¨ç›®å½•
enable = true
# æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
keepStatic = false
# æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
auto = true
# æ˜¯å¦åœ¨ä¾§è¾¹ç›®å½•ä¸­æ˜¾ç¤ºæ ‡é¢˜
showTitle = true


# ä»£ç é…ç½®
[params.page.code]
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
copy = true
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 50
# ä»£ç é«˜äº®ä¸»é¢˜
theme = "github"
# ä»£ç é«˜äº®ä¸»é¢˜çš„æ ·å¼
themeStyle = "monokai"
# æ˜¯å¦æ˜¾ç¤ºè¡Œå·
lineNums = true
# æ˜¯å¦æ˜¾ç¤ºè¡Œå·çš„åŒºåŸŸ
lineNumsStyle = "table"


# è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment]
enable = true
# giscus comment è¯„è®ºç³»ç»Ÿè®¾ç½® (https://giscus.app/zh-CN)
[params.page.comment.giscus]
# ä½ å¯ä»¥å‚è€ƒå®˜æ–¹æ–‡æ¡£æ¥ä½¿ç”¨ä¸‹åˆ—é…ç½®
enable = true
repo = "rinuandengfeng/rinuandengfeng.github.io"
repoId = "R_kgDOJx2X7Q"
category = "Announcements"
categoryId = "DIC_kwDOJx2X7c4CbVcp"
# ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
lang = "zh-CN"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lazyLoading = true
lightTheme = "light"
darkTheme = "dark"


# æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
enable = false


# TypeIt é…ç½®
[params.typeit]
# æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
speed = 100
# å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
cursorSpeed = 1000
# å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
cursorChar = "|"
# æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
duration = -1


# é…ç½®æ–‡ç« æ—¥æœŸ
[frontmatter]
date = ['date', 'pubdate', 'lastmod', 'modified']
lastmod = ['lastmod', 'modified', 'date', 'pubdate']
publishDate = ['pubdate', 'date']

# é…ç½®404é¡µé¢
[[redirects]]
from = '/**'
status = 404
to = '/404.html'
